/*
 * TART Server
 *
 * TART Server
 *
 * OpenAPI spec version: 1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BMIRussian_ru.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class FromTelegramBotRequest : IEquatable<FromTelegramBotRequest>
    { 
        /// <summary>
        /// Temporary token for authentication
        /// </summary>
        /// <value>Temporary token for authentication</value>
        [Required]
        [DataMember(Name="TemporaryToken")]
        public string TemporaryToken { get; set; }

        /// <summary>
        /// Telegram user ID
        /// </summary>
        /// <value>Telegram user ID</value>
        [Required]
        [DataMember(Name="TelegramId")]
        public string TelegramId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FromTelegramBotRequest {\n");
            sb.Append("  TemporaryToken: ").Append(TemporaryToken).Append("\n");
            sb.Append("  TelegramId: ").Append(TelegramId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FromTelegramBotRequest)obj);
        }

        /// <summary>
        /// Returns true if FromTelegramBotRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of FromTelegramBotRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FromTelegramBotRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    TemporaryToken == other.TemporaryToken ||
                    TemporaryToken != null &&
                    TemporaryToken.Equals(other.TemporaryToken)
                ) && 
                (
                    TelegramId == other.TelegramId ||
                    TelegramId != null &&
                    TelegramId.Equals(other.TelegramId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (TemporaryToken != null)
                    hashCode = hashCode * 59 + TemporaryToken.GetHashCode();
                    if (TelegramId != null)
                    hashCode = hashCode * 59 + TelegramId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FromTelegramBotRequest left, FromTelegramBotRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FromTelegramBotRequest left, FromTelegramBotRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}

